# Generated by Django 5.0.6 on 2024-05-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_category', models.CharField(max_length=100)),
                ('store_name', models.CharField(max_length=100)),
                ('original_price', models.FloatField(default=0.0)),
                ('discount_price', models.FloatField(default=0.0)),
                ('discount_amount', models.FloatField(default=0.0)),
                ('product_url', models.CharField(max_length=100)),
                ('is_discounted', models.BooleanField()),
                ('last_updated', models.DateField()),
            ],
        ),
    ]
