# Generated by Django 5.0.6 on 2024-11-28 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_original_price_product_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 11, 28, 19, 10, 28, 559387)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
