# Generated by Django 5.0.6 on 2024-12-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_is_published_product_product_uom_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='current_price',
        ),
        migrations.AddField(
            model_name='product',
            name='is_discounted',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='product',
            name='previous_price',
            field=models.FloatField(default=0.0, editable=False),
        ),
    ]
