# Generated by Django 5.0.6 on 2024-12-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_price_product_current_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_url',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
