# Generated by Django 5.0.2 on 2024-12-20 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ean',
            new_name='ean_code',
        ),
    ]
