# Generated by Django 5.0.6 on 2024-12-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apikey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='user',
            field=models.CharField(default='RaspberryPi', max_length=100),
            preserve_default=False,
        ),
    ]
