# Generated by Django 5.0.4 on 2024-11-29 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_alter_activity_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='activity_desc',
            new_name='activity_description',
        ),
    ]
