# Generated by Django 5.0.4 on 2024-11-29 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitemap', '0002_sitemap_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitemap',
            old_name='active',
            new_name='is_active',
        ),
    ]
